### ISSUE TITLE
Plots issue

### ISSUE THREAD

**Issue by amoazeni75** [LituRout/OptimalTransportModeling#1]
Hi,
Thanks for the repo, I think you forgot to include `src.plotters`
There is no implementation for:
`from src.plotters import plot_noise_interp_unequal, plot_inv_noise_interp_unequal`

**Comment by LituRout** [comment]
Hi Alireza,
Thanks for the pointer. The repository now contains the [src](https://github.com/LituRout/OptimalTransportModeling/tree/main/source/src) folder with these implementations: `from src.plotters import plot_noise_interp_unequal, plot_inv_noise_interp_unequal`. I hope this resolves the plotting issue. 

Let me know if you encounter any other issue.
